# Travis CI integration for p4-spec using Docker.

branches:
  only:
  - master

services:
  - docker

before_install:
  - git config user.name "Travis CI"
  - git config user.email "p4c@barefootnetworks.com"

script:
  - git remote add public git@github.com:p4lang/p4-spec.git
  - git fetch public gh-pages
  - git checkout gh-pages
  - git rebase master
  - docker run -v `pwd`/p4-16/spec:/usr/src/p4-spec p4lang/madoko-debian:sid make

after_success:
  - cp p4-16/spec/build/P4-16-draft-spec.{html,pdf} docs/
  - git commit -m "docs for $TRAVIS_COMMIT" docs/P4-16-draft-spec.{html,pdf}
  - git push public +gh-pages
